# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e27051cbc3ccafd9b03c734699fbbfc32d86c5d8a3aae6d074d31ebc704d5818ea557bf6a44463b9ddf45ce99b400f8e2cd4d8729f9b963467ed3f92351fb2f

test:
  secret_key_base: d76316731ace70d04b5ece6435320b01187c531d7bc02406f54068f063d088ef48d21ee7373aeeaf36e8d85a4d17b4ff671b795bf27c5e45940bceb2479abaee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
